### ISSUE TITLE
Convert invoice to .tiff

### ISSUE THREAD

**Issue by mutusfa** [monetlt/orka#3]
Tesseract works with .tiff format. Assuming we get invoices in .pdf format.

Write/find a micro-service taking .pdf (path to .pdf), returning .tiff (path to .tiff).

For now, working on one file at a time is good enough. We'll see, if we can improve on that later, imo.

**Comment by saulbein** [comment]
Already done (untested) at [orka_engine_preprocess](https://github.com/monetlt/orka/blob/master/orka_engine/orka_engine_preprocessing/src/main.cc)

**Comment by saulbein** [comment]
We will probably need converters from other formats as well, but that can be done later
